# Generated by Django 4.2.4 on 2023-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_time", models.CharField(max_length=45)),
                ("log_file", models.CharField(max_length=45)),
                ("db_file", models.CharField(max_length=45)),
            ],
        ),
    ]
